In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('C17.csv')

In [3]:
data.head()

Test vectors  Expected output
0        x00x0                0
1        xx111               x0
2        x10x0               11
3        x1100               11
4        x10xx               11

In [4]:
data1 = pd.DataFrame()

In [5]:
data1['Test vectors '] = data['Test vectors '].str.replace('x', '0')

In [6]:
data1['Expected output'] = data['Expected output'].str.replace('x', '0')

In [7]:
data2 = pd.DataFrame()

In [8]:
data2['Test vectors '] = data['Test vectors '].str.replace('x', '1')

In [9]:
data2['Expected output'] = data['Expected output'].str.replace('x', '1')

In [10]:
data1.head()

Test vectors  Expected output
0        00000                0
1        00111               00
2        01000               11
3        01100               11
4        01000               11

In [11]:
data2.head()

Test vectors  Expected output
0        10010                0
1        11111               10
2        11010               11
3        11100               11
4        11011               11

In [12]:
final_data = pd.concat([data1, data2], ignore_index=True)

In [13]:
for i in range(len(final_data['Expected output'])):
    if final_data['Expected output'][i] == '0':
        final_data['Expected output'][i] = '00'
    elif final_data['Expected output'][i] == '1':
        final_data['Expected output'][i] = "01"

In [14]:
final_data.head()

Test vectors  Expected output
0        00000               00
1        00111               00
2        01000               11
3        01100               11
4        01000               11

In [15]:
X = final_data.drop('Expected output',axis=1)
y = final_data['Expected output']

In [16]:
X

Test vectors 
0          00000 
1          00111 
2          01000 
3          01100 
4          01000 
..            ...
103        10111 
104        11111 
105        00111 
106        01111 
107        10011 

[108 rows x 1 columns]

In [17]:
y

0      00
1      00
2      11
3      11
4      11
       ..
103    11
104    10
105    01
106    00
107    01
Name: Expected output, Length: 108, dtype: object

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 32)

In [19]:
from sklearn.svm import SVC

In [20]:
model = SVC()

In [21]:
model.fit(X_train,y_train)

SVC()

In [22]:
prediction = model.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
print(confusion_matrix(y_test,prediction))

[[ 4  0  0  0]
 [ 3  0  2  0]
 [ 2  0  6  0]
 [ 6  0 10  0]]


In [25]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

          00       0.27      1.00      0.42         4
          01       0.00      0.00      0.00         5
          10       0.33      0.75      0.46         8
          11       0.00      0.00      0.00        16

    accuracy                           0.30        33
   macro avg       0.15      0.44      0.22        33
weighted avg       0.11      0.30      0.16        33



D:\Users\guntu\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\guntu\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Users\guntu\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
from sklearn.ensemble import RandomForestClassifier
RF_model=RandomForestClassifier()
RF_model.fit(X_train,y_train)

RandomForestClassifier()

In [27]:
rf_prediction=RF_model.predict(X_test)

In [28]:
print(confusion_matrix(y_test,rf_prediction))

[[ 3  1  0  0]
 [ 1  4  0  0]
 [ 0  0  5  3]
 [ 0  0  1 15]]


In [29]:
print(classification_report(y_test,rf_prediction))

              precision    recall  f1-score   support

          00       0.75      0.75      0.75         4
          01       0.80      0.80      0.80         5
          10       0.83      0.62      0.71         8
          11       0.83      0.94      0.88        16

    accuracy                           0.82        33
   macro avg       0.80      0.78      0.79        33
weighted avg       0.82      0.82      0.81        33

